package GUI;


import javax.swing.*;
import java.awt.*;

public class GameForm extends JFrame {

    public JPanel gameScreen;
    public JPanel gameArea;

    public static void main(String[] args) {
        JFrame gameFrame = new JFrame("Tetris 2.0");
        GameForm tetrisGUI = new GameForm();

        tetrisGUI.getGameScreen().setBackground(Color.BLACK);
        gameFrame.add(tetrisGUI.getGameScreen());
        gameFrame.setSize(850, 650);
        gameFrame.setLocation(350, 100);
        gameFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        gameFrame.setVisible(true);
    }

    public JPanel getGameScreen() {
        return gameScreen;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return gameScreen;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        gameScreen = new JPanel();
        gameScreen.setLayout(new GridLayout());
        final JPanel gameArea = new JPanel();
        gameArea.setLayout(new GridLayout());
        gameScreen.add(gameArea, BorderLayout.CENTER);

    }

}
